# Generated by Django 4.1.1 on 2022-09-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_settings", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="States",
            new_name="State",
        ),
    ]
