# Generated by Django 4.1.1 on 2022-09-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_settings", "0004_alter_damagetoaircraft_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="damagetoaircraft",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["import_data_settings", "can import data settings"],
                    ["export_data_settings", "can export data settings"],
                ],
            },
        ),
    ]
