# Generated by Django 4.1.1 on 2022-09-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_settings", "0005_alter_damagetoaircraft_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="damagetoaircraft",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_data_settings", "can deactivate data settings"],
                    ["print_data_settings", "can print data settings"],
                    ["import_data_settings", "can import data settings"],
                    ["export_data_settings", "can export data settings"],
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="highestinjurylevel",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    [
                        "deactivate_highest_injury_level",
                        "can deactivate highest injury level",
                    ],
                    ["print_highest_injury_level", "can print highest injury level"],
                    ["import_highest_injury_level", "can import highest injury level"],
                    ["export_highest_injury_level", "can export highest injury level"],
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="investigationstatus",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    [
                        "deactivate_investigation_status",
                        "can deactivate investigation status",
                    ],
                    ["print_investigation_status", "can print investigation status"],
                    ["import_investigation_status", "can import investigation status"],
                    ["export_investigation_status", "can export investigation status"],
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="occurrencecategory",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    [
                        "deactivate_occurrence_category",
                        "can deactivate occurrence category",
                    ],
                    ["print_occurrence_category", "can print occurrence category"],
                    ["import_occurrence_category", "can import occurrence category"],
                    ["export_occurrence_category", "can export occurrence category"],
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="occurrencetype",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_occurrence_type", "can deactivate occurrence type"],
                    ["print_occurrence_type", "can print occurrence type"],
                    ["import_occurrence_type", "can import occurrence type"],
                    ["export_occurrence_type", "can export occurrence type"],
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="reportstatus",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_report_status", "can deactivate report status"],
                    ["print_report_status", "can print report status"],
                    ["import_report_status", "can import report status"],
                    ["export_report_status", "can export report status"],
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="state",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_state", "can deactivate state"],
                    ["print_state", "can print state"],
                    ["import_state", "can import state"],
                    ["export_state", "can export state"],
                ],
            },
        ),
    ]
