# Generated by Django 4.1.2 on 2022-10-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_settings", "0007_alter_damagetoaircraft_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_airplane", "can deactivate airplane"],
                    ["print_airplane", "can print airplane"],
                    ["import_airplane", "can import airplane"],
                    ["export_airplane", "can export airplane"],
                ],
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_airport", "can deactivate airport"],
                    ["print_airport", "can print airport"],
                    ["import_airport", "can import airport"],
                    ["export_airport", "can export airport"],
                ],
            },
        ),
        migrations.CreateModel(
            name="APIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
                ("endpoint", models.CharField(max_length=1500, unique=True)),
                ("access_key", models.CharField(max_length=1500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_apiprovider", "can deactivate api provider"],
                    ["print_apiprovider", "can print api provider"],
                    ["import_apiprovider", "can import api provider"],
                    ["export_apiprovider", "can export api provider"],
                ],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
                ("url", models.CharField(max_length=1500)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_city", "can deactivate city"],
                    ["print_city", "can print city"],
                    ["import_city", "can import city"],
                    ["export_city", "can export city"],
                ],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_country", "can deactivate country"],
                    ["print_country", "can print country"],
                    ["import_country", "can import country"],
                    ["export_country", "can export country"],
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="damagetoaircraft",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_damagetoaircraft", "can deactivate data settings"],
                    ["print_damagetoaircraft", "can print data settings"],
                    ["import_damagetoaircraft", "can import data settings"],
                    ["export_damagetoaircraft", "can export data settings"],
                ],
            },
        ),
    ]
