# Generated by Django 4.1.2 on 2022-10-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_settings", "0008_airplane_airport_apiprovider_city_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_manufacturer", "can deactivate manufacturer"],
                    ["print_manufacturer", "can print manufacturer"],
                    ["import_manufacturer", "can import manufacturer"],
                    ["export_manufacturer", "can export manufacturer"],
                ],
            },
        ),
    ]
