# Generated by Django 4.1.1 on 2022-10-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aircraft_template_manager",
            "0002_aircrafttemplatemanager_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="aircraft_model",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="engine_count",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="engine_type",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="iata",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="icao_code",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="manufacturer_company_full_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="manufacturer_company_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="model_3d_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="model_3d_image//%Y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="type",
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="wtc",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="year_manufactured",
            field=models.DateField(blank=True, max_length=500, null=True),
        ),
    ]
