# Generated by Django 4.1.1 on 2022-10-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aircraft_template_manager",
            "0003_alter_aircrafttemplatemanager_aircraft_model_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="year_manufactured",
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
    ]
