# Generated by Django 4.1.2 on 2022-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft_template_manager", "0007_manufacturer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircrafttemplatemanager",
            name="source",
            field=models.CharField(
                default="DIRECT", max_length=100, verbose_name="Source of data"
            ),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="aircraft_model",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Aircraft Model"
            ),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="description",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="engine_count",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Engine Count"
            ),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="engine_type",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Engine Type"
            ),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="iata",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="IATA Code"
            ),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="icao_code",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="ICAO CODE"
            ),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active Status"),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="model_3d_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="model_3d_image//%Y/%m/%d",
                verbose_name="Aircraft Image",
            ),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="type",
            field=models.CharField(
                blank=True, max_length=1500, null=True, verbose_name="Aircraft Type"
            ),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="wtc",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Wake Turbulence Category",
            ),
        ),
        migrations.AlterField(
            model_name="aircrafttemplatemanager",
            name="year_manufactured",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Year of manufacture"
            ),
        ),
    ]
