# Generated by Django 4.1.1 on 2022-09-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_administrator_options_alter_committee_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="administrator",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="committee",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="occurrenceareamanager",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="occurrenceowner",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="stakeholder",
            options={"ordering": ["-created_at"]},
        ),
    ]
