# Generated by Django 4.1.1 on 2022-09-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_administrator_options_alter_committee_options_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Administrator",
        ),
        migrations.DeleteModel(
            name="Committee",
        ),
        migrations.DeleteModel(
            name="OccurrenceAreaManager",
        ),
        migrations.DeleteModel(
            name="OccurrenceOwner",
        ),
        migrations.DeleteModel(
            name="Stakeholder",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="user",
            name="type",
        ),
    ]
