# Generated by Django 4.1.1 on 2022-09-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_permissions_can_export_permissions_can_import_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrole",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role")},
        ),
    ]
