# Generated by Django 4.1.1 on 2022-09-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_userrole_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Permissions",
            new_name="Permission",
        ),
    ]
