# Generated by Django 4.1.1 on 2022-09-21 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_permission_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="role",
            name="user",
            field=models.ManyToManyField(
                through="accounts.UserRole", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
