# Generated by Django 4.1.1 on 2022-09-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_rename_can_delete_permission_can_deactivate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
