# Generated by Django 4.1.1 on 2022-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_user_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
