# Generated by Django 4.1.1 on 2022-09-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_role_user_alter_userrole_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_user", "can deactivate user"],
                    ["print_user", "can print user"],
                    ["import_user", "can import user"],
                    ["export_user", "can export user"],
                ],
            },
        ),
    ]
