# Generated by Django 4.1.2 on 2022-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
