# Generated by Django 4.1.2 on 2022-10-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_settings", "0009_manufacturer"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccurrenceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, unique=True)),
                ("occurrence_number", models.CharField(max_length=200, unique=True)),
                ("event_phase", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("departure", models.CharField(blank=True, max_length=200)),
                ("destination", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "highest_injury_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_settings.highestinjurylevel",
                    ),
                ),
                (
                    "investigation_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_settings.investigationstatus",
                    ),
                ),
                (
                    "occurrence_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_settings.occurrencecategory",
                    ),
                ),
                (
                    "occurrence_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_settings.occurrencetype",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_settings.state",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_occurrencereport", "can deactivate occurrence report"],
                    ["print_occurrencereport", "can print occurrence report"],
                    ["import_occurrencereport", "can import occurrence report"],
                    ["export_occurrencereport", "can export occurrence report"],
                ],
            },
        ),
    ]
