# Generated by Django 4.1.2 on 2022-10-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereport",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
